#!/usr/bin/env python3
"""First-run bootstrap: write .env with fresh secrets for the demo stack.

Generates everything the demo needs — the paired HS256 secret, the transfer
secret, a quota-admin token, gitea's secret key, and the bundled-MinIO
credentials + bucket name. There are no S3 or URL blanks to fill in — the demo
is self-contained on localhost.

If /work/.env exists, exit 0 silently so later `compose up`s are no-ops. If it
doesn't, write one and exit non-zero so dependent services don't boot with the
empty values compose already substituted — the operator re-runs `compose up`.
"""

import base64
import os
import secrets
import sys

ENV_PATH = "/work/.env"


def main() -> int:
    if os.path.exists(ENV_PATH):
        print(f"[bootstrap] {ENV_PATH} already exists, nothing to do.")
        return 0

    # baleforgit-server verifies the gitea-minted JWT with its own copy of the
    # HS256 key, so the two encodings must decode to the same 32 raw bytes.
    jwt_bytes = secrets.token_bytes(32)
    jwt_hex = jwt_bytes.hex()
    jwt_b64url = base64.urlsafe_b64encode(jwt_bytes).decode().rstrip("=")

    # The published MinIO host port. It appears in two coupled places below — the
    # client-facing presign endpoint and MINIO_S3_PORT — so derive both from one
    # value (compose doesn't expand ${} inside .env values, so the presign URL
    # can't reference MINIO_S3_PORT and must be written with the literal port).
    minio_s3_port = 9000

    contents = f"""# Generated by scripts/bootstrap.py. Not committed (see .gitignore).
# Rotate every secret by deleting this file and re-running `compose up`.

# ===== Secrets (auto-generated — keep private) ==============================

# Paired HS256 secret: the SAME 32 bytes, hex for baleforgit-server and
# base64url for gitea. gitea mints the JWT that baleforgit-server verifies.
BALE_JWT_SECRET_HEX={jwt_hex}
LFS_JWT_SECRET_BASE64URL={jwt_b64url}

# HMAC key for baleforgit-server signed download URLs (exactly 32 bytes hex).
BALE_TRANSFER_SECRET_HEX={secrets.token_bytes(32).hex()}

# Admin bearer shared by the server (BALE_ADMIN_TOKEN_HEX) and gitea
# (GITEA__bale__ADMIN_TOKEN): gitea reads GET /v1/usage/{{owner}} for the repo
# storage panel, and it gates PUT /v1/quotas/{{owner}}.
BALE_ADMIN_TOKEN_HEX={secrets.token_bytes(32).hex()}

# gitea session/cookie key.
GITEA_SECRET_KEY={secrets.token_urlsafe(48)}

# ===== Bundled MinIO (the demo's S3 backend) ================================
# Root credentials — also used by baleforgit-server to authenticate to MinIO,
# and to log into the MinIO console at http://localhost:9001.
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD={secrets.token_urlsafe(24)}

# Bucket baleforgit-server reads/writes.
BALE_S3_BUCKET=bale

# Endpoint signed into the presigned download URLs clients fetch (the server
# itself reaches MinIO in-network at minio:9000, which the client can't resolve).
# Single-host demo: the published localhost port. Multi-host: change to a LAN IP
# or domain the client machines can reach — keep its port equal to MINIO_S3_PORT.
BALE_S3_PUBLIC_ENDPOINT_URL=http://localhost:{minio_s3_port}

# ===== Host ports (change if any clash with something already running) ======
# Container ports are fixed; these only move the published HOST side. Two are
# special: MINIO_S3_PORT is published 1:1 because presigned URLs embed it, and
# GITEA_SSH_PORT is both gitea's SSH listen port and what clone URLs advertise.
GITEA_HTTP_PORT=3000
GITEA_SSH_PORT=2222
BALE_HTTP_PORT=8080
MINIO_S3_PORT={minio_s3_port}
MINIO_CONSOLE_PORT=9001
"""

    with open(ENV_PATH, "w") as f:
        f.write(contents)
    os.chmod(ENV_PATH, 0o600)

    print(f"[bootstrap] wrote {ENV_PATH} with fresh secrets.")
    print("[bootstrap] re-run `compose up -d` to start the demo stack.")
    # Non-zero on purpose: blocks dependent services this run, so they don't
    # start with the empty env vars compose already substituted before the
    # file existed.
    return 1


if __name__ == "__main__":
    sys.exit(main())
